spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alexandrina_aksp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Egor2004}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: ${SHOW_SQL:true}
        format_sql: ${FORMAT_SQL:true}
        hbm2ddl:
          auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: ${MAX_SIZE:5GB}
      max-request-size: ${MAX_SIZE:5GB}
  profiles:
    active: ${PROFILES:dev}
logging:
  level:
    root: info


app:
  video:
    bucket: ${VIDEO_BUCKET:C:/Users/Egor/IdeaProjects/alexandrina-aksp/videos/}
    extension: ${VIDEO_EXTENSION:.mp4}
    portion-size: ${VIDEO_PORTION:5Mb}
server:
  port: 8081
